version: '2'

services:
  hubot:
    image: lowet84/hubot
    build: ./
    volumes:
     - /etc/localtime:/etc/localtime:ro
    ports:
     - 8089:8080
    restart: always
    environment:
     - REDIS_URL=redis://redis:6379
     - HUBOT_LOG_LEVEL=debug
     - MESSENGER_VERIFY_TOKEN=$MESSENGER_VERIFY_TOKEN
     - MESSENGER_ACCESS_TOKEN=$MESSENGER_ACCESS_TOKEN
    labels:
     - traefik.backend=hubot
     - traefik.frontend.passHostHeader=true
     - traefik.port=8080
     - traefik.frontend.rule=Host:hubot.fredriklowenhamn.se
  redis:
    image: redis
    ports:
     - 6379:6379
    volumes:
     - /volumes/redis:/data
     - /etc/localtime:/etc/localtime:ro
