version: '2'
services:
  mysql:
    image: mysql
    ports:
      - 3306
    restart: always
    volumes:
      - /volumes/guacamole:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gurkburk

  mysql-init:
    image: lowet84/mysql-guacamole-init
    volumes:
     - /volumes/guacamole:/data
    environment:
      PASSWORD: gurkburk

  guacd:
    image: glyptodon/guacd
    restart: always

  guacamole:
    image: lowet84/guacamole
    ports:
      - 8000:8080
    restart: always
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
      MYSQL_HOSTNAME: mysql
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    labels:
      - traefik.backend=guacamole
      - traefik.frontend.passHostHeader=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:guacamole.fredriklowenhamn.se

